[INFO    ] [Client  ] Initializing client
None
Traceback (most recent call last):
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\http.py", line 247, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\http.py", line 214, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/jakub/Desktop/freefbot/src/client.py", line 28, in <module>
    client.run(Config.token)
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\client.py", line 572, in run
    return task.result()
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\client.py", line 492, in _silence_gathered
    fut.result()
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\client.py", line 479, in start
    await self.login(*args, bot=bot)
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\client.py", line 352, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\jakub\.virtualenvs\freefbot-ll76MV-T\lib\site-packages\discord\http.py", line 251, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
